### ISSUE TITLE
Migrate heroku.rb calls to platform-api

### ISSUE THREAD

**Issue by mattpolito** [mattpolito/paratrooper#78]
Currently heroku.rb is being used to make all calls to heroku. Look into moving these calls to the [heroku platform-api](https://devcenter.heroku.com/articles/platform-api-reference). (Most likely utilizing their [platform-api library](https://github.com/heroku/platform-api))

Luckily all calls to heroku are isolated to the `HerokuWrapper`. This means that the underlining code there could be manipulated without much/any change to the rest of the library.

**Comment by plicjo** [comment]
the feels

**Comment by pixiitech** [comment]
Matt, is there any hope of merging this? Heroku is discontinuing their v2 API next month.

**Comment by mattpolito** [comment]
@pixiitech Thanks for the heads up, I will take a look at it again.

**Comment by brandoncc** [comment]
They sunsetted v2 API today...

**Comment by mattpolito** [comment]
@brandoncc this issue didn't get updated but was fixed in #86.
